language: php

php:
  - 5.6
  - 7.0

sudo: false

services:
  - mysql

cache:
    directories:
        - node_modules

before_install:
  - nvm install 5.1
  - gem update --system
  - gem install compass

before_script:
  - mkdir -p storage/framework/{cache,views,sessions}
  - cp .env.travis .env
  - mysql -e 'create database laravel;' -uroot

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry npm install

script:
  - php artisan migrate --force --seed
  - php artisan key:generate
  - php artisan cache:clear
  - php artisan config:clear
  - php artisan view:clear
  - php artisan clear-compiled
  - gulp
  - vendor/bin/phpunit

deploy:
  - provider: script
    skip_cleanup: true
    script: deploy.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: php artisan migrate
    on:
      branch: develop
