language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

services:
  - mysql

before_install:
  - nvm install 5.1

before_script:
  - cp .env.example .env
  - mysql -e 'create database laravel;'
  - export DB_DATABASE=laravel
  - export DB_USERNAME=travis
  - export DB_PASSWORD=
  - php artisan key:generate

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry npm install

script:  
  - php artisan migrate --force
  - gulp
  - vendor/bin/phpunit
