language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

services:
  - mysql

cache:
    directories:
        - node_modules

before_install:
  - nvm install 5.1
  - gem update --system
  - gem install compass

before_script:
  - mkdir -p storage/framework/{cache,views,sessions}
  - cp .env.travis .env
  - mysql -e 'create database laravel;'
  - export DB_DATABASE=laravel
  - export DB_USERNAME=travis
  - export DB_PASSWORD=
  - php artisan key:generate
  - php artisan cache:clear
  - php artisan config:clear
  - php artisan view:clear
  - php artisan clear-compiled


install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry npm install

script:
  - php artisan migrate --force --seed
  - gulp
  - gulp phpcs
  - vendor/bin/phpunit
